/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-20 10:17:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class memberlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1662604091462L));
    _jspx_dependants.put("jar:file:/C:/java0711/javawork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMiniProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/java0711/javawork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMiniProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Anton&family=Edu+VIC+WA+NT+Beginner:wght@600&family=Gamja+Flower&family=Single+Day&family=Jua&family=Nanum+Pen+Script&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.0.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	*{\r\n");
      out.write("		font-family: 'Jua';\r\n");
      out.write("		/* background-color: #121212; */\r\n");
      out.write("		/* color: #bbb; */\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	\r\n");
      out.write("	<!-- <h1>memberlist 화면</h1> -->\r\n");
      out.write("	<h4 class=\"alert alert-secondary\">총 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("명의 회원이 있습니다</h4>\r\n");
      out.write("	<br>\r\n");
      out.write("	<table class=\"table table-bordered\">\r\n");
      out.write("		");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	</table>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 로그인창 -->\r\n");
      out.write("	<!-- The Modal -->\r\n");
      out.write("	<div class=\"modal\" id=\"myUpdateModal\">\r\n");
      out.write("	  <div class=\"modal-dialog\">\r\n");
      out.write("	    <div class=\"modal-content\">\r\n");
      out.write("	\r\n");
      out.write("	      <!-- Modal Header -->\r\n");
      out.write("	      <div class=\"modal-header\">\r\n");
      out.write("	        <h4 class=\"modal-title\">회원정보 수정</h4>\r\n");
      out.write("	        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("	      </div>\r\n");
      out.write("	\r\n");
      out.write("	      <!-- Modal body -->\r\n");
      out.write("	      <div class=\"modal-body\">\r\n");
      out.write("	        <div class=\"input-group mb-3 input-group-sm\">\r\n");
      out.write("			  <span class=\"input-group-text\" style=\"width: 80px;\">회원명</span>\r\n");
      out.write("			  <input type=\"text\" class=\"form-control\" id=\"updatename\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-group mb-3 input-group-sm\">\r\n");
      out.write("			  <span class=\"input-group-text\" style=\"width: 80px;\">연락처</span>\r\n");
      out.write("			  <input type=\"text\" class=\"form-control\" id=\"updatehp\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-group mb-3 input-group-sm\">\r\n");
      out.write("			  <span class=\"input-group-text\" style=\"width: 80px;\">이메일</span>\r\n");
      out.write("			  <input type=\"email\" class=\"form-control\" id=\"updateemail\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-group mb-3 input-group-sm\">\r\n");
      out.write("			  <span class=\"input-group-text\" style=\"width: 80px;\">주소</span>\r\n");
      out.write("			  <input type=\"text\" class=\"form-control\" id=\"updateaddr\">\r\n");
      out.write("			</div>\r\n");
      out.write("	      </div>\r\n");
      out.write("	\r\n");
      out.write("	      <!-- Modal footer -->\r\n");
      out.write("	      <div class=\"modal-footer\">\r\n");
      out.write("	        <button type=\"button\" class=\"btn btn-success\" data-bs-dismiss=\"modal\" id=\"btnupdateok\">수정</button>\r\n");
      out.write("	        <button type=\"button\" class=\"btn btn-danger\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("	      </div>\r\n");
      out.write("	\r\n");
      out.write("	    </div>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(\".btnnewphoto\").click(function () {\r\n");
      out.write("			$(\"#newphoto\").trigger(\"click\");\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#newphoto\").change(function () {\r\n");
      out.write("			var num=$(this).attr(\"num\");\r\n");
      out.write("			console.log(num);\r\n");
      out.write("			\r\n");
      out.write("			var form=new FormData();\r\n");
      out.write("			form.append(\"photo\",$(\"#newphoto\")[0].files[0]);	//선택한 1개만 추가\r\n");
      out.write("			form.append(\"num\",num);\r\n");
      out.write("			console.dir(form);\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type: \"post\",	//반환 안받음\r\n");
      out.write("				dataType:\"text\",\r\n");
      out.write("				url:\"updatephoto\",\r\n");
      out.write("				processData:false,\r\n");
      out.write("				contentType:false,\r\n");
      out.write("				data:form,\r\n");
      out.write("				success:function(res){\r\n");
      out.write("					\r\n");
      out.write("					location.reload();\r\n");
      out.write("				}	//success 종료\r\n");
      out.write("				\r\n");
      out.write("			});	//ajax 종료\r\n");
      out.write("		}); //사진수정 버튼 이벤트 종료\r\n");
      out.write("		\r\n");
      out.write("		//멤버 삭제\r\n");
      out.write("		$(\".btndelete\").click(function () {\r\n");
      out.write("			\r\n");
      out.write("			var num=$(this).attr(\"num\");\r\n");
      out.write("			//alert(num);\r\n");
      out.write("			\r\n");
      out.write("			var ans=confirm(\"정말 탈퇴하시겠습니까?\");\r\n");
      out.write("			if(ans){\r\n");
      out.write("				\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					type: \"get\",	//반환 안받음\r\n");
      out.write("					dataType:\"text\",\r\n");
      out.write("					url:\"delete\",\r\n");
      out.write("					//processData:false,\r\n");
      out.write("					//contentType:false,\r\n");
      out.write("					data:{\"num\":num},\r\n");
      out.write("					success:function(res){\r\n");
      out.write("						\r\n");
      out.write("						alert(\"탈퇴가 완료되었습니다\")\r\n");
      out.write("						location.reload();\r\n");
      out.write("					}	//success 종료\r\n");
      out.write("					\r\n");
      out.write("				}); //ajax 종료\r\n");
      out.write("			} //if 종료\r\n");
      out.write("		}); //delete 버튼이벤트 종료\r\n");
      out.write("		\r\n");
      out.write("		//수정 버튼 클릭 시 데이터 가져오기\r\n");
      out.write("		$(\".btnupdate\").click(function () {\r\n");
      out.write("			updatenum=$(this).attr(\"num\");	//일부러 var 안씀.. 왜?\r\n");
      out.write("			//alert(updatenum);\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type: \"get\",\r\n");
      out.write("				dataType:\"json\",\r\n");
      out.write("				url:\"updateform\",\r\n");
      out.write("				data:{\"num\":updatenum},\r\n");
      out.write("				success:function(res){\r\n");
      out.write("					console.dir(res);\r\n");
      out.write("					$(\"#updatename\").val(res.name);\r\n");
      out.write("					$(\"#updatehp\").val(res.hp);\r\n");
      out.write("					$(\"#updateemail\").val(res.email);\r\n");
      out.write("					$(\"#updateaddr\").val(res.address);\r\n");
      out.write("					\r\n");
      out.write("				}	//success 종료\r\n");
      out.write("				\r\n");
      out.write("			}); //ajax 종료\r\n");
      out.write("			\r\n");
      out.write("		});	//update버튼 이벤트 종료\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		//수정\r\n");
      out.write("		$(\"#btnupdateok\").click(function () {\r\n");
      out.write("			\r\n");
      out.write("			var updatename=$(\"#updatename\").val();\r\n");
      out.write("			var updatehp=$(\"#updatehp\").val();\r\n");
      out.write("			var updateemail=$(\"#updateemail\").val();\r\n");
      out.write("			var updateaddr=$(\"#updateaddr\").val();\r\n");
      out.write("			\r\n");
      out.write("			var data=\"num=\"+updatenum+\"&name=\"+updatename+\"&hp=\"+updatehp+\"&email=\"+updateemail+\"&address=\"+updateaddr;\r\n");
      out.write("			console.log(data);\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type: \"post\",	//반환 안받음\r\n");
      out.write("				dataType:\"text\",\r\n");
      out.write("				url:\"update\",\r\n");
      out.write("				data:data,\r\n");
      out.write("				success:function(res){\r\n");
      out.write("					\r\n");
      out.write("					location.reload();\r\n");
      out.write("				}	//success 종료\r\n");
      out.write("				\r\n");
      out.write("			});	//ajax 종료\r\n");
      out.write("			\r\n");
      out.write("		}); //btnupdate 버튼 이벤트 종료\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/member/memberlist.jsp(30,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("dto");
      // /WEB-INF/member/memberlist.jsp(30,2) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/member/memberlist.jsp(30,2) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("	<!-- 번호 없으니까 varstatus 필요없음 -->\r\n");
            out.write("			<tr>\r\n");
            out.write("				<td style=\"width: 250px;\" align=\"center\" rowspan=\"5\">\r\n");
            out.write("					<img src=\"../upload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" width=\"230\" height=\"250\" border=\"1\">\r\n");
            out.write("					<br>\r\n");
            out.write("					<!-- 여기서 forEach 반복문 안에 id값들을 줬지만 쓰지말아야함 (ID는 고유값인데 반복하면 같은iD가 여러개됨 -->\r\n");
            out.write("					<!-- 2022 09 20 id로 부여되어있던걸 클래스로 수정함 -->\r\n");
            out.write("					\r\n");
            out.write("					<br>\r\n");
            out.write("					\r\n");
            out.write("					<!-- 로그인 상태에서 본인의 수정/삭제버튼 보이게 -->\r\n");
            out.write("					");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("				</td>\r\n");
            out.write("				<td style=\"width: 300px;\">회원명 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("				<td rowspan=\"5\" align=\"center\" valign=\"middle\">\r\n");
            out.write("					<!-- 로그인 상태에서 본인의 수정/삭제버튼 보이게 -->\r\n");
            out.write("					");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("				</td>\r\n");
            out.write("			</tr>\r\n");
            out.write("			<tr>\r\n");
            out.write("				<td>아이디 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.loginid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("			</tr>\r\n");
            out.write("			<tr>\r\n");
            out.write("				<td>이메일 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("			</tr>\r\n");
            out.write("			<tr>\r\n");
            out.write("				<td>핸드폰 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.hp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("			</tr>\r\n");
            out.write("			<tr>\r\n");
            out.write("				<td>주소 : ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("			</tr>\r\n");
            out.write("		");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/member/memberlist.jsp(41,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginok!=null and sessionScope.loginid==dto.loginid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<input type=\"file\" id=\"newphoto\" style=\"display: none;\" num=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"> <!-- 사진 수정 시 호출 -->\r\n");
          out.write("						<button type=\"button\" class=\"btn btn-secondary btnnewphoto\">사진 수정</button>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/member/memberlist.jsp(49,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginok!=null and sessionScope.loginid==dto.loginid}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<button type=\"button\" class=\"btn btn-secondary btnupdate\" num=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"\r\n");
          out.write("						data-bs-toggle=\"modal\" data-bs-target=\"#myUpdateModal\">수정</button>\r\n");
          out.write("						<br><br>\r\n");
          out.write("						<button type=\"button\" class=\"btn btn-danger btndelete\" num=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">삭제</button>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
