/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-23 05:38:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boarddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1662604091462L));
    _jspx_dependants.put("jar:file:/C:/java0711/javawork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMiniProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/java0711/javawork/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SpringMiniProject/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fitems_005fdelims;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fitems_005fdelims = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fitems_005fdelims.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Anton&family=Edu+VIC+WA+NT+Beginner:wght@600&family=Gamja+Flower&family=Single+Day&family=Jua&family=Nanum+Pen+Script&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.0.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	*{\r\n");
      out.write("		font-family: 'Jua';\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	span.likes{\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	span.day{\r\n");
      out.write("		color: #333;\r\n");
      out.write("		float: right;\r\n");
      out.write("		font-size: 0.9em;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	span.writer{\r\n");
      out.write("		color: red;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("		border: 1px solid red;\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		margin-left: 5px;\r\n");
      out.write("		font-size: 0.9em;\r\n");
      out.write("		padding: 3px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.adel{\r\n");
      out.write("		color: red;\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("		margin-left: 5px;\r\n");
      out.write("		font-size: 0.8em;\r\n");
      out.write("		font-weight: bold;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.alist pre{\r\n");
      out.write("		text-indent: 10px;\r\n");
      out.write("		color: gray;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	div.alist img{\r\n");
      out.write("		width: 40px;\r\n");
      out.write("		height: 40px;\r\n");
      out.write("		cursor: pointer;\r\n");
      out.write("		border: 1px solid gray;\r\n");
      out.write("		border-radius: 10px;\r\n");
      out.write("		margin-left: 10px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("	var num=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";	//전역변수 선언\r\n");
      out.write("	\r\n");
      out.write("	$(function () {\r\n");
      out.write("		console.log(\"num=\"+num);\r\n");
      out.write("		\r\n");
      out.write("		list();	//처음 시작 시 출력\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	function list() {\r\n");
      out.write("		\r\n");
      out.write("		var loginok='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginok}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("		var loginid='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';	//로그인 한 사람의 아이디\r\n");
      out.write("		var writeid='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';	//글쓴 사람의 아이디 \r\n");
      out.write("		\r\n");
      out.write("		//alert(loginok+\",\"+loginid);\r\n");
      out.write("		\r\n");
      out.write("		var s=\"\";\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			url:\"../answer/list\",\r\n");
      out.write("			dataType:\"json\",\r\n");
      out.write("			data:{\"num\":num},\r\n");
      out.write("			success:function(res){\r\n");
      out.write("				\r\n");
      out.write("				//댓글 갯수부터 출력해보기\r\n");
      out.write("				$(\"b.banswer\").text(res.length);	//배열로 넘어오니까 length가 개수\r\n");
      out.write("				\r\n");
      out.write("				$.each(res, function(i, elt) {\r\n");
      out.write("					s+=\"<div style='border-top:1px solid lightgray;'>\"+name+elt.name;\r\n");
      out.write("					\r\n");
      out.write("					if(elt.photo!='no')\r\n");
      out.write("						{\r\n");
      out.write("							s+=\"<a href='../upload/\"+elt.photo+\"' target='_blank'>\";\r\n");
      out.write("							s+=\"<img src='../upload/\"+elt.photo+\"'>\";\r\n");
      out.write("							s+=\"</a>\";\r\n");
      out.write("						}\r\n");
      out.write("					\r\n");
      out.write("					if(writeid==elt.id){	//로그인 한 사람과 작성자가 같으면 댓글에 '작성자'표시\r\n");
      out.write("						s+=\"<span class='writer'>작성자</span>\";	\r\n");
      out.write("					}\r\n");
      out.write("					s+=\"<br>\";\r\n");
      out.write("					s+=\"<pre>\"+elt.message\r\n");
      out.write("					s+=\"<span class='day'>\"+elt.writeday+\"&nbsp;\";\r\n");
      out.write("					\r\n");
      out.write("					if(loginok=='yes' && loginid==elt.id){\r\n");
      out.write("						s+='<i class=\"material-icons adel\" idx='+elt.idx+'>close </i>';\r\n");
      out.write("					}\r\n");
      out.write("					\r\n");
      out.write("					s+=\"</prd></span></div>\";\r\n");
      out.write("					\r\n");
      out.write("				});	//each 반복 종료\r\n");
      out.write("				\r\n");
      out.write("				$(\"div.alist\").html(s);\r\n");
      out.write("				\r\n");
      out.write("			}	//success 종료\r\n");
      out.write("			\r\n");
      out.write("		});	//ajax 종료\r\n");
      out.write("		\r\n");
      out.write("	} //function list 종료\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<table class=\"table table-bordered\" style=\"width: 600px;\">\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>\r\n");
      out.write("				<h2><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.subject}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></h2>\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('(');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</b><br>\r\n");
      out.write("				<span style=\"color: #ccc; font-size: 13px;\">\r\n");
      out.write("					");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					&nbsp;&nbsp;\r\n");
      out.write("					조회&nbsp;");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.readcount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("				</span>\r\n");
      out.write("				\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		<tr height=\"300\" valign=\"top\">\r\n");
      out.write("			<td>\r\n");
      out.write("				<pre>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.content}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</pre>\r\n");
      out.write("				<br><br>\r\n");
      out.write("				");
      out.write("\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<br><br>\r\n");
      out.write("				<span class=\"likes\">\r\n");
      out.write("					<!-- <i class='fas fa-heart'></i> -->\r\n");
      out.write("					<i class='far fa-heart'></i>&nbsp;\r\n");
      out.write("					좋아요 <b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.likes}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></span>\r\n");
      out.write("					&nbsp;&nbsp;\r\n");
      out.write("					\r\n");
      out.write("				<i class='far fa-comment-dots'></i>\r\n");
      out.write("				&nbsp;<b class=\"banswer\">댓글 0</b>\r\n");
      out.write("				\r\n");
      out.write("				<br>\r\n");
      out.write("				<div class=\"alist\" style=\"margin-top: 20px;\">\r\n");
      out.write("					댓글목록\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		<tr>\r\n");
      out.write("			<td>\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-outline-secondary\"\r\n");
      out.write("				onclick=\"location.href='form'\">새글</button>\r\n");
      out.write("				\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-outline-secondary\"\r\n");
      out.write("				onclick=\"location.href='form?num=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&regroup=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.regroup}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&restep=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.restep}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&relevel=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.relevel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&currentPage=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">답글</button>\r\n");
      out.write("				\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-outline-secondary\"\r\n");
      out.write("				onclick=\"location.href='list?currentPage=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">목록</button>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				<!-- 로그인중이면서, 세션ID와 글작성자와 같다면 수정/삭제 가능하도록(보이도록) -->\r\n");
      out.write("				");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				\r\n");
      out.write("			</td>\r\n");
      out.write("		</tr>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("	</table>\r\n");
      out.write("	\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	\r\n");
      out.write("		//하트 클릭 시 빨강하트 & 빈하트 번갈아 나오게 하기\r\n");
      out.write("		$(\"span.likes\").click(function () {\r\n");
      out.write("\r\n");
      out.write("			var heart=$(this).find(\"i\").attr(\"class\"); //i태그로하면 안되는경우가 있어서, class로 주기\r\n");
      out.write("			if(heart=='far fa-heart'){\r\n");
      out.write("				$(this).find(\"i\").attr(\"class\",\"fas fa-heart\").css(\"color\",\"red\");\r\n");
      out.write("			}else{\r\n");
      out.write("				$(this).find(\"i\").attr(\"class\",\"far fa-heart\").css(\"color\",\"black\");\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("		//ajax 이용해서 좋아요 수 증가 후 출력\r\n");
      out.write("		var num=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("		console.log(num);\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			url:\"likes\",\r\n");
      out.write("			dataType:\"json\",\r\n");
      out.write("			data:{\"num\":num},\r\n");
      out.write("			success:function(res){\r\n");
      out.write("				\r\n");
      out.write("				$(\"span.likes\").find(\"b\").text(res.likes);\r\n");
      out.write("				\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("	});	//이벤트 종료\r\n");
      out.write("	\r\n");
      out.write("	//댓글의 사진 버튼\r\n");
      out.write("	$(\"#btnphoto\").click(function () {\r\n");
      out.write("		$(\"#upload\").trigger(\"click\");\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//file 태그\r\n");
      out.write("	$(\"#upload\").change(function () {\r\n");
      out.write("		var form=new FormData();\r\n");
      out.write("		form.append(\"photo\",$(\"#upload\")[0].files[0]);	//선택한 1개만 추가\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type: \"post\",	//반환 안받음\r\n");
      out.write("			dataType:\"json\",	//map으로 보냈음\r\n");
      out.write("			url:\"../answer/updatephoto\",\r\n");
      out.write("			processData:false,\r\n");
      out.write("			contentType:false,	//멀티파트 폼데이터\r\n");
      out.write("			data:form,\r\n");
      out.write("			success:function(res){\r\n");
      out.write("				\r\n");
      out.write("				console.log(res.aphoto);\r\n");
      out.write("				\r\n");
      out.write("				//upload사진을 #aphoto에 출력\r\n");
      out.write("				$(\"#aphoto\").attr(\"src\",\"../upload/\"+res.aphoto);\r\n");
      out.write("				$(\"#aphoto\").css(\"display\",\"inline-block\");\r\n");
      out.write("				\r\n");
      out.write("			} //success 종료\r\n");
      out.write("			\r\n");
      out.write("		}); //ajax 종료\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	//댓글 저장\r\n");
      out.write("	$(\"#btnsave\").click(function () {\r\n");
      out.write("		var fdata=$(\"#aform\").serialize();	//form태그 안의 name을 쿼리스트링 형태로 읽어온다\r\n");
      out.write("		//alert(fdata);\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"post\",\r\n");
      out.write("			url:\"../answer/insert\",\r\n");
      out.write("			dataType:\"text\", //void 이므로 json이 아닌 text\r\n");
      out.write("			data:fdata,	//fdata는 쿼리스트링 형태\r\n");
      out.write("			success:function(res){\r\n");
      out.write("				\r\n");
      out.write("				list();	//댓글 목록을 다시 db에서 가져와서 출력\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("				//입력값이랑 사진 안보이게 처리\r\n");
      out.write("				$(\"#message\").val(\"\");	//메세지 value 값 비우기\r\n");
      out.write("				$(\"#aphoto\").attr(\"src\",\"\").css(\"display\",\"none\");	//aphoto 의 src 비우고, 안보이게하기 \r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	//댓글 삭제\r\n");
      out.write("	$(document).on(\"click\", \".adel\", function () {\r\n");
      out.write("		\r\n");
      out.write("		confirm(\"댓글을 삭제하시겠습니까?\");\r\n");
      out.write("\r\n");
      out.write("		var idx=$(this).attr(\"idx\");\r\n");
      out.write("		\r\n");
      out.write("		console.log(idx);\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			url:\"../answer/delete\",\r\n");
      out.write("			dataType:\"text\", //void 이므로 json이 아닌 text\r\n");
      out.write("			data:{\"idx\":idx},\r\n");
      out.write("			success:function(res){\r\n");
      out.write("				\r\n");
      out.write("				list();	//댓글 목록을 다시 db에서 가져와서 출력\r\n");
      out.write("			 	\r\n");
      out.write("	\r\n");
      out.write("			} //res 종료\r\n");
      out.write("			\r\n");
      out.write("		});	//ajax 종료\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("		\r\n");
      out.write("	</script>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/board/boarddetail.jsp(141,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memphoto!='no'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(" <!-- 탈퇴한 회원은 사진 안나옴 -->\r\n");
          out.write("					<img src=\"../upload/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memphoto}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" width=\"50\" height=\"50\" class=\"rounded-circle\"\r\n");
          out.write("					align=\"left\" onerror=\"this.src='../image/noimage.png'\" hspace=\"20\">\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /WEB-INF/board/boarddetail.jsp(149,5) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.writeday}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/board/boarddetail.jsp(149,5) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/board/boarddetail.jsp(161,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.photo!='no'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("					");
          if (_jspx_meth_c_005fforTokens_005f0(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforTokens_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forTokens
    org.apache.taglibs.standard.tag.rt.core.ForTokensTag _jspx_th_c_005fforTokens_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForTokensTag) _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fitems_005fdelims.get(org.apache.taglibs.standard.tag.rt.core.ForTokensTag.class);
    boolean _jspx_th_c_005fforTokens_005f0_reused = false;
    try {
      _jspx_th_c_005fforTokens_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforTokens_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/board/boarddetail.jsp(162,5) name = items type = javax.el.ValueExpression reqTime = true required = true fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/board/boarddetail.jsp(162,5) '${dto.photo}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${dto.photo}",java.lang.String.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/board/boarddetail.jsp(162,5) name = delims type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforTokens_005f0.setDelims(",");
      int[] _jspx_push_body_count_c_005fforTokens_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforTokens_005f0 = _jspx_th_c_005fforTokens_005f0.doStartTag();
        if (_jspx_eval_c_005fforTokens_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write(" \r\n");
            out.write("						<img src=\"../upload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.photo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" width=\"250\" class=\"img-thumbnail\"\r\n");
            out.write("						onerror=\"this.style.display='none'\"> <!-- 해당 폴더에 없는 사진은 안보이게 처리 -->\r\n");
            out.write("					");
            int evalDoAfterBody = _jspx_th_c_005fforTokens_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforTokens_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforTokens_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforTokens_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforTokens_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforTokens_0026_005fitems_005fdelims.reuse(_jspx_th_c_005fforTokens_005f0);
      _jspx_th_c_005fforTokens_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforTokens_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforTokens_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/board/boarddetail.jsp(184,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginok!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				\r\n");
          out.write("				<div class=\"aform\">\r\n");
          out.write("					<form id=\"aform\">\r\n");
          out.write("						<input type=\"hidden\" name=\"num\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("						<input type=\"hidden\" name=\"id\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("						<input type=\"hidden\" name=\"name\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("						\r\n");
          out.write("						<input type=\"file\" id=\"upload\" style=\"display: none;\">\r\n");
          out.write("						<button type=\"button\" class=\"btn btn-success btn-sm\" id=\"btnphoto\">사진</button>\r\n");
          out.write("						<img src=\"\" id=\"aphoto\" width=\"50\" height=\"50\" style=\"display: none;\"> \r\n");
          out.write("						\r\n");
          out.write("						<br>\r\n");
          out.write("						\r\n");
          out.write("						<div class=\"input-group\">\r\n");
          out.write("							<textarea name=\"message\" id=\"message\" style=\"width: 400px;height: 70px; margin-top: 10px;\"\r\n");
          out.write("							class=\"form-control\"></textarea>\r\n");
          out.write("							<button type=\"button\" class=\"btn btn-secondary btn-sm\" id=\"btnsave\" style=\"margin-top: 10px;\">등록</button>\r\n");
          out.write("						</div>\r\n");
          out.write("						<!-- ajax는 id로 읽음 -->\r\n");
          out.write("						<!-- json은 name 으로 읽음 -->\r\n");
          out.write("					</form>\r\n");
          out.write("				</div>\r\n");
          out.write("				\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/board/boarddetail.jsp(227,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginok!=null && sessionScope.loginid==dto.id}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				\r\n");
          out.write("					<button type=\"button\" class=\"btn btn-outline-secondary\"\r\n");
          out.write("					onclick=\"location.href='updateform?num=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&currentPage=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">수정</button>\r\n");
          out.write("					\r\n");
          out.write("					<button type=\"button\" class=\"btn btn-outline-secondary\"\r\n");
          out.write("					onclick=\"location.href='delete?num=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.num}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&currentPage=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">삭제</button>\r\n");
          out.write("				");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
